# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEQMjgTeg19Xfu_mlFpbeWMpiF72tphQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data=pd.read_csv("/content/StudentHoursScores.csv")
data

print(data.head())

print(data.dtypes)

print(data.columns)

data.size

print(data.shape)

print(data.tail())

data.info()

type(data)

data.min()

data.max()

data.describe()

data.iloc[2:6]

print(data.corr())

data.nunique()

x=data["Hours"]
y=data["Scores"]
plt.xlabel("Hours")
plt.ylabel("Scores")
plt.scatter(x,y,marker='+',color='red')
plt.show()

x = data.iloc[:,0:-1]
y = data.iloc[:,-1]
print(x.head())
print(y.head())
print(x.shape,y.shape)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2,random_state=1)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

from sklearn.linear_model import LinearRegression
model=LinearRegression()

my=model.fit(xtrain,ytrain)

xtrain.shape

y_pre=my.predict(xtest)
y_pre

ytest

xtest

print(my.coef_)

print(my.intercept_)

from sklearn.metrics import r2_score, mean_squared_error
print("accuracy is: ", r2_score(ytest,y_pre))
print("mean_squared_error: ",mean_squared_error(ytest,y_pre))

total= 1/1-(r2_score(ytest,y_pre))
total

